@startuml FireFlyDA rev.0.2

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN

Person(user, "User")
Person(sitecore, "SiteCore")

System_Boundary(c1, "Private hub"){
    Container(hub_app, "Web Application", "Angular, C# MVC", "Allows users to view contacts, activities, properties, etc.")
    ContainerDb(rel_db, "Relational Database", "SQL x.x.x", "hub Database\nContact Staging Area")
    Container(hsvc, "QueueService", "C#", "Subscribes to queue")

    'Internal Relationships
    Rel(user, hub_app, "Uses", "HTTPS")
    Rel(hub_app, rel_db, "Reads From\nWrites To")
    Rel(hsvc, rel_db, "Writes To")  
}

System_Boundary(c2, "Public HoldingArea"){
    Container(web_api, "Web API", "Azure Function, C# ", "")
    Container(store, "Azure Storage Queue", "Azure", "Queues Contact in Canonical form")   
    Container(svc, "Service", "Azure Function, C#", "Collects content from external services")

    'Internal Relationships
    Rel(sitecore, web_api, "Uses", "HTTPS") 

    Rel_L(web_api, store, "Writes To")
    Rel_U(svc, store, "Writes To")
}

' External Systems
System_Ext(ExternalSystem, "External Systems\nGiosq\nResponseTap") 

' External Relationships
Rel(hsvc, store, "Subscribes To\nReads From")
Rel(svc, ExternalSystem, "ExternalSystem", "HTTPS")


@enduml
