@startuml FireFlyDA

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN

Person(user, "User")
Person(sched, "Scheduler")
Person(sitecore, "SiteCore")

System_Boundary(c1, "Private hub"){
    Container(hub_app, "Web Application", "Angular, C# MVC", "Allows users to view contacts, activities, properties, etc.")
    ContainerDb(rel_db, "Relational Database", "SQL x.x.x", "hub Database\nContact Staging Area")
    Container(svc, "Service", "C#", "Collects content from external services")
}

System_Boundary(c2, "Public HoldingArea"){
    Container(web_api, "Web API", "Azure Function, Logic App, C# ", "")
    Container(store, "Azure Storage Table", "Azure", "Stores Contact in Canonical form")   

}

Rel(sched, svc, "Uses", "HTTPS") 
Rel(user, hub_app, "Uses", "HTTPS")
Rel(hub_app, rel_db, "Reads from\nand writes to")
Rel(svc, web_api, "Reads from")
Rel(svc, rel_db, "Reads from\nand writes to")

' External Systems
System_Ext(ExternalSystem, "External Systems\nGiosq\nResponseTap") 

' Relationships

Rel(sitecore, web_api, "Uses", "HTTPS") 
Rel(web_api, store, "Reads from\nWrites To")
'Rel_U(svc, store, "Writes to")
Rel(svc, ExternalSystem, "ExternalSystem", "HTTPS")

@enduml
