@startuml Application Component
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(web_app, "Web Application"){
    Component( api, "Web API", "link") 
    Component( act, "Activities", "")
    Component( app, "Appointments", "")
    Component( con, "Contacts", "")

    Rel(api, act, "Uses")
    Rel(api, app, "Uses")
    Rel(api, con, "Uses")

    Rel(act, app, "Uses")
    Rel(con, app, "Uses")

}

Container_Boundary(data, "Data Layer"){
    Container(sto, "Azure Storage", "Azure", "Stores system artifacts")
    ContainerDb(rel_db, "Relational Database", "SQL x.x.x", "Stores Entities")
    ContainerDb(es, "ElasticSearch", "ES x.x.x", "Search Indexing")

    sto -[hidden]right- rel_db
    rel_db -[hidden]right- es
}

app -[hidden]- rel_db

System(int_systems, "Qube")
Rel_R(app, int_systems, "Qube", "HTTPS")

@enduml