@startuml Application annotation
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title System Context diagram for KF hub Property Portfolio System

Person(user  , KF User , "<$user> <$mobile_user>\n A User within KnightFrank" )

System_Boundary(hub_system, "hub"){
    Container(web_app, "Web Application", "Angular", "Allows users to view contacts, activities, properties, etc.")
    Container(web_api, "Web API", "C# MVC", "Allows users to view contacts, activities, properties, etc.")
    Container(filesystem, "Azure Storage", "Azure", "Stores system artifacts")
    ContainerDb(rel_db, "Relational Database", "SQL x.x.x", "Stores Entities")
    ContainerDb(es, "ElasticSearch", "ES x.x.x", "Search Indexing")
    Container(webjob, "Webjob", "Azure c# webjob", "Updates content on a scheduled and triggered basis")
}

System(int_systems, "Internal Systems")
System_Ext(ext_systems, "External Systems")

' Relationships
Rel(user, web_app, "Uses", "HTTPS")
Rel(web_app, web_api, "Uses", "HTTPS")

Rel(web_api, rel_db, "Reads from\nand writes to")
Rel(web_api, filesystem, "Reads from\n and writes to")
Rel(web_api, es, "Reads from\n")

Rel_U(webjob, rel_db, "Reads from\nand writes to")
Rel_U(webjob, filesystem, "Reads from\nand writes to")
Rel_U(webjob, es, "Reads from\nand writes to")

Rel_Back(user, int_systems, "Sends e-mails to")
Rel(web_app, int_systems, "InternalSystem", "HTTPS/HTTP")
Rel(webjob, int_systems, "InternalSystem", "HTTPS/HTTP")
Rel(webjob, ext_systems, "ExternalSystem", "HTTPS")

@enduml

