@startuml Application Component
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(web_app, "Web Application"){
        Component( api, "Web API", "link")  [[http://plantuml.com]]
        Component( pro, "Properties", "")
        Component( act, "Activities", "")
        Component( app, "Appointments", "")
        Component( are, "AreaBreakdown", "")
        Component( att, "Attachments", "")
        Component( not, "Notes", "")
        Component( off, "Offer", "")
        Component( own, "Ownership", "")
        Component( ast, "Asset", "")
        Component( ten, "Tenancies", "")

        Rel(api, pro, "Uses")
        Rel(pro, act, "Uses")
        Rel(pro, app, "Uses")
        Rel(pro, are, "Uses")
        Rel(pro, att, "Uses")
        Rel(pro, not, "Uses")
        Rel(pro, off, "Uses")
        Rel(pro, own, "Uses")
        Rel(pro, ast, "Uses")
        Rel(pro, ten, "Uses")
}

Container_Boundary(search, "Search"){
    Component( sast, "Asset", "")
    Component( snot, "Note", "")

    sast -[hidden]right- snot
}

Container_Boundary(data, "Data Layer"){
    Container(sto, "Azure Storage", "Azure", "Stores system artifacts")
    ContainerDb(rel_db, "Relational Database", "SQL x.x.x", "Stores Entities")
    ContainerDb(es, "ElasticSearch", "ES x.x.x", "Search Indexing")

    sto -[hidden]right- rel_db
    rel_db -[hidden]right- es
}

search -[hidden]right- data

act -[hidden]- sast
'not -[hidden]- rel_db
ten -[hidden]- es

System(int_systems, "Qube")
Rel_L(app, int_systems, "Qube", "HTTPS")

  
@enduml
