@startuml Application Component
!include <c4/C4_Component.puml>  
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>
LAYOUT_TOP_DOWN

Container_Boundary(web_app, "Web Application"){
        Component( api, "Web API", "link")  [[http://plantuml.com]]
        Component( pro, "Properties", "")
        Component( act, "Activities", "")
        Component( app, "Appointments", "")
        Component( are, "AreaBreakdown", "")
        Component( att, "Attachments", "")
        Component( not, "Note", "")
        Component( off, "Offer", "")
        Component( own, "Ownership", "")
        Component( ast, "Asset", "")
        Component( ten, "Tenancies", "")

        Rel(api, pro, "Uses")
        Rel(pro, act, "Uses")
        Rel(pro, app, "Uses")
        Rel(pro, are, "Uses")
        Rel(pro, att, "Uses")
        Rel(pro, not, "Uses")
        Rel(pro, off, "Uses")
        Rel(pro, own, "Uses")
        Rel(pro, ast, "Uses")
        Rel(pro, ten, "Uses")
}

Container_Boundary(data, "Data Layer"){
    Container(sto, "Azure Storage", "Azure", "Stores system artifacts")
    ContainerDb(rel_db, "Relational Database", "SQL x.x.x", "Stores Entities")
    ContainerDb(es, "ElasticSearch", "ES x.x.x", "Search Indexing")

    sto -[hidden]right- rel_db
    rel_db -[hidden]right- es
}

act -[hidden]- sto
not -[hidden]- rel_db
ten -[hidden]- es
  
@enduml
