@startuml
class TenancySubAgentMapper {
}
class "BaseMultiplePartyWithGenericDescriptionMapper`3"<T1,T2,T3> {
}
class "ITenancyMultiplePartiesMapper`1"<T> {
}
"BaseMultiplePartyWithGenericDescriptionMapper`3" "<TenancyPartyCommand,TenancyParty,TenancySubAgent>" <|-- TenancySubAgentMapper
"ITenancyMultiplePartiesMapper`1" "<TenancySubAgent>" <|-- TenancySubAgentMapper
@enduml
