@startuml WIP System rev0.3

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <tupadr3/common>
!include <azure/AzureCommon.puml>
!include <azure/Storage/AzureQueueStorage>
!include <azure/Web/AzureWebApp>
!include <azure/Compute/AzureFunction>

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml

LAYOUT_LEFT_RIGHT
LAYOUT_WITH_LEGEND()

Title Hub<->SAP Configuration (Proposed rev-03)

Person( wipUser, "Wip\nUser", "")
Person( repUser, "Reporting\nUser", "")

System_Ext( sap, "SAP Working Life", "")

System_Boundary(c1, "hub"){
    Container(hub_app, "Web Application", "Angular", "Allows users to view contacts, activities, properties, etc.", "angular")
    Container(hub_api, "Web Application", "C#", "Allows users to view contacts, activities, properties, etc.", "AzureWebApp")
    AzureFunction(webjob, "Notification Process", "Queue Trigger")
    ContainerDb(db, "Database", "Microsoft SQL", "hub Database", "msql_server")

    Container( sapOutQueue, "Sap UpSert Queue", "", "", "AzureQueueStorage")
    Container( sapInQueue, "Sap Notification Queue", "", "", "AzureQueueStorage")

    hub_app --> hub_api 
    hub_api -right-> db
    hub_api --> sapOutQueue

    webjob <-- sapInQueue
    webjob -left-> db

}
System_Boundary(c2, "Azure"){
    Container( sapSvc, "SapService", "", "")
}

c1 -[hidden]-> c2
sapOutQueue --> sapSvc
sapInQueue <-- sapSvc

sapSvc <--> sap

wipUser --> hub_app
repUser --> hub_app

@enduml