@startuml "Tenancy Deposit Scheme"

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Integration/AzureEventGrid.puml
!includeurl AzurePuml/Storage/AzureQueueStorage.puml

LAYOUT_LEFT_RIGHT
LAYOUT_WITH_LEGEND()

Container(hub, Hub, "Hub Web API")
Container(WebJob, WebJob, "Hub Web Job")
ContainerDb(Sql, Sql, "Hub Sql")
Container(hubNote, Notification, "Hub Notification")

AzureQueueStorage(InQ, "InBound Queue", "Storage Queue")
AzureQueueStorage(OutQ, "OutBound Queue", "Storage Queue")
AzureQueueStorage(PeQ, "Pending Queue", "Storage Queue")
AzureQueueStorage(CoQ, "Complete Queue", "Storage Queue")

AzureFunction(fnCreate, "Create", "Queue Trigger")
AzureFunction(fnStatus, "Status", "Timer Trigger")
AzureFunction(fnCert, "Get Deposit Protection Cert", "C#")

System_Ext(Tds, "Tenancy Deposit Scheme")

InQ --> fnCreate
fnCreate --> Tds : Create Request
fnStatus --> Tds : Status Request
fnCert --> Tds : Deposit Protection Certificate Request 

fnCreate -> PeQ
PeQ -> fnStatus : Status - Pending
PeQ <- fnStatus : Insert
fnStatus -> CoQ : Complete
CoQ -> fnCert : Status - Complete

OutQ <-- fnCert
hub --> InQ
WebJob <-- OutQ

hubNote <-- WebJob
Sql <-- WebJob


@enduml