@startuml HomePpl Service

Details -> hub
hub -> SvcQueue
SvcQueue -> Svc
Activate Svc

alt Creation
Svc -> Tds : Post Deposit protection Create
else Update
Svc -> Tds : Post Deposit protection Update
end

alt Success=True
Svc <-- Tds : Response 2xx Success
Svc -> Table : Update details in Table Store
else Success=False
Svc <-- Tds : Response 2xx Data Error
Svc -> Table : Update details in Table Store
Svc -> SvcQueue : Return Data Error to hub
end
Deactivate Svc

== Every Hour ==
Svc -> Table : Get Messages in non Compete state
Activate Svc
Loop Through Messages
    Svc -> Tds : Get Status Update
    group Success=True
        Svc <-- Tds : Response 200
        Svc -> Table : Store details in a table
        group Status = Complete
            Svc -> Tds : Get Certificate URL
            group Success=True
                Svc <-- Tds : Respond 200
                Svc -> Table : Store details in a table
                Svc -> SvcQueue : Return Data to hub
            else Success=False
                Svc <-- Tds : Respond 200
                Svc -> Table : Store details in a table
                Svc -> SvcQueue : Return Data Error to hub
            end
        end
    else Success=False
        Svc <-- Tds : Respond 200
        Svc -> Table : Store details in a table
        Svc -> SvcQueue : Return Data Error to hub
    end

End
Deactivate Svc


@enduml