@startuml TennancyProgressionDb

left to right direction

!define table(x) class x << (T,mistyrose) >>   
!define view(x) class x << (V,lightblue) >>   
!define table(x) class x << (T,mistyrose) >>  
!define tr(x) class x << (R,red) >>  
!define tf(x) class x << (F,darkorange) >>   
!define af(x) class x << (F,white) >>   
!define fn(x) class x << (F,plum) >>   
!define fs(x) class x << (F,tan) >>   
!define ft(x) class x << (F,wheat) >>   
!define if(x) class x << (F,gaisboro) >>   
!define p(x) class x << (P,indianred) >>   
!define pc(x) class x << (P,lemonshiffon) >>   
!define x(x) class x << (P,linen) >>     
!define primary_key(x) <<pk>> <u>x</u>
!define foreign_key(x) <<fk>> <b>x</b>
!define link( k, y) k }--||  y
hide methods   
hide stereotypes  
skinparam classarrowcolor gray  

table( Address)
{
    primary_key(Id)
}

table( Reference)
{
    primary_key(Id)
}

table( MapReferenceContact)
{
    primary_key(Id)
    ReferenceId
    ContactId
}

MapReferenceContact <-- Contact
MapReferenceContact <-- Reference 

table( Contact)
{
    primary_key(Id)
    Type
    Name
    Address
    ReferencesId
    IndividualId
    CompanyId
}

Contact --> Address

table( Company)
{
    primary_key(Id)
}

table( Individual)
{
    primary_key(Id)
    DOB
}

Contact <-- Company
Contact <-- Individual


table( Tenant)
{
    primary_key(Id)
}

table( Property)
{
    primary_key(Id)
    Name
    AddressId
    OwnerId
    Type
}

table( PropertyDetails)
{
    primary_key(Id)
    Address
    Spaces
    BuildingTitle
    EPC
}

PropertyDetails --> Reference : BuildingTitle
PropertyDetails --> Reference : EPC
PropertyDetails --> Address : AddressId

table( MapTenantProperty)
{
    primary_key(Id)
    ContactId
    PropertyId
    TennacyDetails
}

Property --> PropertyDetails 
Property --> Contact : OwnerId
MapTenantProperty <-- Property : PropertyId
MapTenantProperty <-- Contact : ContactId
MapTenantProperty --> TennacyDetails

table(TennacyDetails)
{
    primary_key(Id)
    StartDate
    EndDate
    Duration
    RentId
    Unit
    NoncommissionableRent
    NoncommissionableRentDescription
    LanlordLivesIn
    TennancyType
    RentIncreaseId
}

table( RentIncrease)
{
    primary_key(Id)

}


@enduml