@startuml FMLottery
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

'Person, Person_Ext, System, System_Ext, SystemDb, 
'SystemDb_Ext, Boundary, System_Boundary, Enterprise_Boundary
'Container, ContainerDb, Container_Boundary

Person(User, "User")

System_Boundary(Lottery, "Lottery") {
    Container(SPA, "Single Page Application", "Provides all the Lottery analysis via their browser")
    Container(API, "Web API", "Provises lottery Information via HTTPS/Json API")
    ContainerDb(LotteryDb, "Data Store", "Stores lottery information for analysis")
    
    Rel(SPA, API, "Makes calls To", "HTTPS/JSON")
    Rel_L(API, LotteryDb, "Reads From /\n Writes To", "ODBC")  
}

System_Ext(Camalot,"Camalot","UK Lottery Provider")

Rel(User, SPA, "Uses", "HTTPS/JSON")
Rel_R(API, Camalot, "Uses", "HTTPS/JSON")  
@enduml