@startuml FMLottery
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

'Person, Person_Ext, System, System_Ext, SystemDb, 
'SystemDb_Ext, Boundary, System_Boundary, Enterprise_Boundary
'Container, ContainerDb, Container_Boundary
'Component, ComponentDb

Container(SPA, "Single Page Application", "Provides all the Lottery analysis via their browser")

Container_Boundary(WebAPI, "Web API") {

Container_Boundary( ThunderBall, "Thunderball") {
    Component( TBU, "Update","","")
    Component( TBP, "Prediction","","")
    Component( TBC, "Collection","","")
}

    Component( TTS, "ThunderBall Repository","","")
    Component( TDS, "ThunderBall Data Service","","")
'    Component( ThunderBall, "ThunderBall","Handles requests for thunderball information","")
}

Component( TableStore, "TableStore","","")
ContainerDb(LotteryDb, "Data Store", "Stores lottery information for analysis")
System_Ext(Camalot,"Camalot","UK Lottery Provider")

    Rel(SPA, ThunderBall, "Makes calls To", "HTTPS/JSON")
    Rel(ThunderBall, TTS, "Uses", "HTTPS/JSON")
    Rel(ThunderBall, TDS, "Uses", "HTTPS/JSON")

    Rel(TableStore, LotteryDb, "Reads From / Writes To", "ODBC")  
    Rel_L(TTS, TableStore, "Uses", "HTTPS/JSON")  
    Rel_R(TDS, Camalot, "Uses", "HTTPS/JSON")  
@enduml