@startuml Activity Image Commands


Left To Right Direction

class ActivityMarketingImageCommandResult {
    + ShouldSynchronizeToQube : bool <<get>> <<set>>
}
class "IEnumerable"<T> {
}
IQubeSynchronizationCommandResult <|-- ActivityMarketingImageCommandResult
ActivityMarketingImageCommandResult --> "ActivityId" Guid
ActivityMarketingImageCommandResult --> "ImagesIds<Guid>" "IEnumerable"

class CreateActivityMarketingImageCommand {
    + Version : int <<get>> <<set>>
}
class "IRequest"<T> {
}
class "IEnumerable"<T> {
}
"IRequest" "<ActivityMarketingImageCommandResult>" <|-- CreateActivityMarketingImageCommand
ICommandWithVersion <|-- CreateActivityMarketingImageCommand
CreateActivityMarketingImageCommand --> "ActivityId" Guid
CreateActivityMarketingImageCommand --> "Images<CreateMarketingImageCommand>" "IEnumerable"
CreateActivityMarketingImageCommand --> "CopiedImages<Guid>" "IEnumerable"

class DeleteActivityMarketingImageCommand {
    + Version : int <<get>> <<set>>
}
class "IRequest"<T> {
}
"IRequest" "<ActivityMarketingImageCommandResult>" <|-- DeleteActivityMarketingImageCommand
ICommandWithVersion <|-- DeleteActivityMarketingImageCommand
DeleteActivityMarketingImageCommand --> "ActivityId" Guid
DeleteActivityMarketingImageCommand --> "ImageId" Guid

class UpdateActivityMarketingImageOrderCommandValidator {
    + UpdateActivityMarketingImageOrderCommandValidator()
}
class "AbstractValidator"<T> {
}
"AbstractValidator" "<UpdateActivityMarketingImageOrderCommand>" <|-- UpdateActivityMarketingImageOrderCommandValidator

class UpdateActivityMarketingImageOrderCommand {
    + Version : int <<get>> <<set>>
}
class "IRequest"<T> {
}
class "IEnumerable"<T> {
}
"IRequest" "<ActivityMarketingImageCommandResult>" <|-- UpdateActivityMarketingImageOrderCommand
ICommandWithVersion <|-- UpdateActivityMarketingImageOrderCommand
UpdateActivityMarketingImageOrderCommand --> "ActivityId" Guid
UpdateActivityMarketingImageOrderCommand --> "Images<UpdateMarketingImageOrderCommand>" "IEnumerable"

class UpdateActivityMarketingImageDescCommand {
    + Description : string <<get>> <<set>>
    + Version : int <<get>> <<set>>
}
class "IRequest"<T> {
}
"IRequest" "<Guid>" <|-- UpdateActivityMarketingImageDescCommand
ICommandWithVersion <|-- UpdateActivityMarketingImageDescCommand
UpdateActivityMarketingImageDescCommand --> "ActivityId" Guid
UpdateActivityMarketingImageDescCommand --> "ImageId" Guid

class UpdateMarketingImageOrderCommandValidator {
    + UpdateMarketingImageOrderCommandValidator()
}
class "AbstractValidator"<T> {
}
"AbstractValidator" "<UpdateMarketingImageOrderCommand>" <|-- UpdateMarketingImageOrderCommandValidator
class UpdateMarketingImageOrderCommand {
    + Order : int <<get>> <<set>>
}
class "IRequest"<T> {
}
"IRequest" "<Guid>" <|-- UpdateMarketingImageOrderCommand
UpdateMarketingImageOrderCommand --> "ImageId" Guid


class MarketingImageDetailQueryResult {
    + ImageName : string <<get>> <<set>>
    + Order : int <<get>> <<set>>
    + Size : long <<get>> <<set>>
    + SmallThumbnailUrl : string <<get>> <<set>>
    + MediumThumbnailUrl : string <<get>> <<set>>
    + ImageUrl : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
}
MarketingImageDetailQueryResult --> "Id" Guid
MarketingImageDetailQueryResult --> "ExternalDocumentId" Guid
MarketingImageDetailQueryResult --> "CreationTime" DateTimeOffset
MarketingImageDetailQueryResult --> "User" UserCardViewModel

class MarketingImageQueryResult {
    + ImageName : string <<get>> <<set>>
    + Order : int <<get>> <<set>>
    + Size : long <<get>> <<set>>
    + ThumbnailUrl : string <<get>> <<set>>
}
MarketingImageQueryResult --> "Id" Guid
MarketingImageQueryResult --> "ImageId" Guid
MarketingImageQueryResult --> "CreationTime" DateTimeOffset
MarketingImageQueryResult --> "User" UserCardViewModel

'Package KnightFrank.Antares
'class ActivitiesController

'Package KnightFrank.Antares.Domain
'class ActivityMarketingImageDetailQueryHandler
'class ActivityMapperProfile
'class MarketingImageDetailQueryResult

@enduml