@startuml   Activity Image Command Handler

Left To Right Direction

class CreateActivityMarketingImageCommandHandler {
    + CreateActivityMarketingImageCommandHandler()
    + Handle(message:CreateActivityMarketingImageCommand) : ActivityMarketingImageCommandResult
}
class "IRequestHandler"<T1,T2> {
}
"IRequestHandler" "<CreateActivityMarketingImageCommand,ActivityMarketingImageCommandResult>" <|-- CreateActivityMarketingImageCommandHandler

class DeleteActivityMarketingImageCommandHandler {
    + DeleteActivityMarketingImageCommandHandler()
    + Handle(message:DeleteActivityMarketingImageCommand) : ActivityMarketingImageCommandResult
}
class "IRequestHandler"<T1,T2> {
}
"IRequestHandler" "<DeleteActivityMarketingImageCommand,ActivityMarketingImageCommandResult>" <|-- DeleteActivityMarketingImageCommandHandler

class UpdateActivityMarketingImageOrderCommandHandler {
    + UpdateActivityMarketingImageOrderCommandHandler()
    + Handle(message:UpdateActivityMarketingImageOrderCommand) : ActivityMarketingImageCommandResult
}
class "IRequestHandler"<T1,T2> {
}
"IRequestHandler" "<UpdateActivityMarketingImageOrderCommand,ActivityMarketingImageCommandResult>" <|-- UpdateActivityMarketingImageOrderCommandHandler

class MarketingImagesOrderChangedEvent {
}
INotification <|-- MarketingImagesOrderChangedEvent
MarketingImagesOrderChangedEvent --> "ActivityId" Guid

class ActivityMarketingImageQuery {
}
class "IRequest"<T> {
}
"IRequest" "<IEnumerable<MarketingImageQueryResult>>" <|-- ActivityMarketingImageQuery
ActivityMarketingImageQuery --> "ActivityId" Guid

class ActivityMarketingImageDetailQuery {
}
class "IRequest"<T> {
}
"IRequest" "<MarketingImageDetailQueryResult>" <|-- ActivityMarketingImageDetailQuery
ActivityMarketingImageDetailQuery --> "ActivityId" Guid
ActivityMarketingImageDetailQuery --> "ImageId" Guid

class ActivityMarketingImageDetailQueryHandler {
    + ActivityMarketingImageDetailQueryHandler()
    + Handle(imageQuery:ActivityMarketingImageDetailQuery) : MarketingImageDetailQueryResult
}
class "IRequestHandler"<T1,T2> {
}
"IRequestHandler" "<ActivityMarketingImageDetailQuery,MarketingImageDetailQueryResult>" <|-- ActivityMarketingImageDetailQueryHandler

class ActivityMarketingImageQueryHandler {
    + ActivityMarketingImageQueryHandler()
    + Handle(imageQuery:ActivityMarketingImageQuery) : IEnumerable<MarketingImageQueryResult>
}
class "IRequestHandler"<T1,T2> {
}
"IRequestHandler" "<ActivityMarketingImageQuery,IEnumerable<MarketingImageQueryResult>>" <|-- ActivityMarketingImageQueryHandler

@enduml