@startuml
left to right direction
!include .\\TenancyFeeSplitCollectionValidator.puml
!include .\\TenancyFeeValidator.puml
!include .\\TenancyMapperProfile.puml
!include .\\CommandHandlers\CreateRightToRentCommandHandler.puml
!include .\\CommandHandlers\CreateTenancyAppointmentCommandHandler.puml
!include .\\CommandHandlers\CreateTenancyAttachmentCommandHandler.puml
!include .\\CommandHandlers\CreateTenancyCommandHandler.puml
!include .\\CommandHandlers\CreateTenancyNoteCommandHandler.puml
!include .\\CommandHandlers\CreateTenancyPartyCommandHandler.puml
!include .\\CommandHandlers\DeleteRightToRentCommandHandler.puml
!include .\\CommandHandlers\DeleteTenancyAttachmentCommandHandler.puml
!include .\\CommandHandlers\DeleteTenancyCommandHandler.puml
!include .\\CommandHandlers\DeleteTenancyPartyCommandHandler.puml
!include .\\CommandHandlers\QubeUpdateTenancyCommandHandler.puml
!include .\\CommandHandlers\SendTenancyToQubeCommandHandler.puml
!include .\\CommandHandlers\SetPassedToQubeCommandHandler.puml
!include .\\CommandHandlers\UpdateRightToRentCommandHandler.puml
!include .\\CommandHandlers\UpdateTenancyAppointmentCommandHandler.puml
!include .\\CommandHandlers\UpdateTenancyAttachmentCommandHandler.puml
!include .\\CommandHandlers\UpdateTenancyCommandHandler.puml
!include .\\CommandHandlers\UpdateTenancyNegotiatorCommandHandler.puml
!include .\\CommandHandlers\UpdateTenancyPartyCommandHandler.puml

@enduml
