@startuml CDDProcess

title CDD-Process

(Start) --> (Request)
(Request) --> CDD
(Request) -[#0000FF]-> (Northrow) : Get CDD before making an Offer
(Northrow) -[#0000FF]-> (Request)  
  
CounterParty --> (Accept)
(Offer) --> CounterParty
CounterParty --> (Reject)

CDD --> Offer
CDD --> (Withdraw)
(Withdraw) --> CounterParty : Notify

(Accept) --> Negotiator : Additional Info
(Accept) --> (Instruction) : Update
Negotiator -[#0000FF]-> (Complete) : Is this Correct ?
(Instruction) --> (Complete) 

(Reject) --> (Notify)
(Withdraw) --> (Notify)

(Notify) --> (Request)
(Notify) --> (End)

(Complete) --> (End)

@enduml