@startuml CDDProcess

title CDD-Process

(Start) --> (Request)
(Request) --> CDD
(Request) -[#0000FF]-> (Northrow) : Get CDD before \nmaking an Offer
(Northrow) -[#0000FF]-> (Request)  
  
CDD --> (Offer) : Approves
CDD --> (Withdraw) : Actions
CDD --> (Reject) : Actions

(Offer) --> CounterParty  
(Withdraw) --> CounterParty : Notify
CounterParty --> (Accept) : Communicates
CounterParty --> (Reject) : Communicates

(Accept) --> (Complete)
(Accept) --> Negotiator : Additional Info
(Accept) --> (Instruction) : Update
Negotiator -[#0000FF]-> (Complete) : Is this Correct ?
(Instruction) --> (Complete) 

(Reject) --> (Complete)
(Withdraw) --> (Complete)

(Complete) --> (Dashboard) : Update
(Complete) --> (Report) : Update
(Dashboard) --> CDD : Notify
(Complete) --> (end)

@enduml