@startuml CDDProcess

title CDD-Process

(Start) --> (Offer)
(Offer) --> (Accept) : 1, Instruction\nCompleted
(Accept) --> (CDD Request) : 2, Trigger CDD Request
(Accept) --> Negotiator : 3, Add\nInformation
(CDD Request) --> (DashBoard) : 4, CDD Request
(DashBoard) --> CDD_Admin
CDD_Admin --> CDD_Officer : 5, Assign
(Offer) --> (Withdraw) 
(Withdraw) --> CDD_Officer : 6. Notify
(CDD Request) --> CDD_Officer : 7. Confirm and Check
CDD_Officer --> (Completed)
(Completed) --> (Activity Status) : 8. Exchanged/Completed
(Activity Status) --> (end)
@enduml