@startuml EIP GDPR Encrypt
!includeurl https://raw.githubusercontent.com/aheil/EIP-PlantUML/master/dist/EIP-PlantUML.puml

LAYOUT_LEFT_RIGHT()

ContentFilter(cf2, "Encrypt") <<$claim_check>> 

rectangle "Db Column" as dc
rectangle "System Secret\n(Salt)" as ss
rectangle "Encrypted: Db Column" as edc

dc --> cf2
ss --> cf2
cf2 --> edc

@enduml