@startuml EIP GDPR Encrypt
!includeurl https://raw.githubusercontent.com/aheil/EIP-PlantUML/master/dist/EIP-PlantUML.puml

LAYOUT_LEFT_RIGHT()

title Encrypt
Aggregator(ag ,"Create User Key")
ContentFilter(cf1, "Unique Key") <<$claim_check>> 
ContentFilter(cf2, "Encrypt Column") <<$claim_check>> 

rectangle "First Name" as ip1
rectangle "Surname" as ip2
rectangle "Email Address" as ip3
rectangle "System Secret" as ss
rectangle "Db Column" as dc
rectangle "Encrypted: Db Column" as edc

ip1 --> ag
ip2 --> ag
ip3 --> ag

ag --> cf1
ss --> cf1
cf1 --> cf2
dc --> cf2

cf2 --> edc

@enduml