@startuml

title "Elastic Search Update - Sequence Diagram"

actor hub
Database  SQL
hub -> SQL
return Id
Queue StorageQueue
hub -> StorageQueue : Save Id
Webjob -> StorageQueue : Get Id
Webjob -> SQL : Get Data
return
Database ElasticSearch
Webjob -> ElasticSearch : Send Data
return


@enduml