@startuml Hub Redirect
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
!includeurl AzurePuml/Networking/AzureTrafficManager.puml
!includeurl AzurePuml/Storage/AzureStorage.puml
!includeurl AzurePuml/Security/AzureKeyVault.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml

title Hub Redriect

!includeurl AzurePuml/AzureSimplified.puml
LAYOUT_LEFT_RIGHT


System_Boundary(1off, "Office 365") {
    Component(1out, "", "Outlook", "Contact")
}

System_Boundary(A1z, "Azure") {
    AzureTrafficManager(1tm, "Hub-Redirect-tm-env-ne", "Global")
    System_Boundary(1rgNe, "Northern Europe") {
        AzureFunction(1afNe, "Hub-Redirect-fn-env-ne", "Northern Europe")
        AzureStorage(1stNe, "Hub-Redirect-st-env-ne", "Northern Europe")
        AzureApplicationInsights( 1aiNe, "Hub-Redirect-ai-env-ne", "Northern Europe")
    }

    System_Boundary(1rgWe, "Western Europe") {
        AzureFunction(1afWe, "Hub-Redirect-fn-env-we", "Western Europe")
        AzureStorage( 1stWe, "Hub-Redirect-st-env-we", "Western Europe")
        AzureApplicationInsights( 1aiWe, "Hub-Redirect-ai-env-we", "Western Europe")
    }
    System_Boundary(1kf, "Private Knight frank ") {
        AzureVirtualMachine(1vm, "https://env.hub.knightfrank.com/", "Env")
    }
}


1out --> 1tm

1tm --> 1afNe
1afNe --> 1stNe
1afNe --> 1aiNe
1vm <-- 1afNe
1tm --> 1afWe
1afWe --> 1stWe
1afWe --> 1aiWe
1vm <-- 1afWe


@enduml