@startuml Hub Redirect
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
!includeurl AzurePuml/Networking/AzureTrafficManager.puml
!includeurl AzurePuml/Storage/AzureStorage.puml
!includeurl AzurePuml/Security/AzureKeyVault.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml

title Hub Redriect

LAYOUT_TOP_DOWN

System_Boundary(off, "Office 365") {
    Component(out, "", "Outlook", "Contact")
}


System_Boundary(Az, "Azure") {

    System_Boundary(rg, "Resource Group") {
        AzureTrafficManager(tm, "Hub-Redirect-tm-env-ne", "Global")

        System_Boundary(rgNe, "Northern Europe") {
            AzureFunction(afNe, "Hub-Redirect-fn-env-ne", "Northern Europe")
            AzureStorage(stNe, "Hub-Redirect-st-env-ne", "Northern Europe")
            AzureApplicationInsights( aiNe, "Hub-Redirect-ai-env-ne", "Northern Europe")

            afNe --> stNe : App/Log Storage
            afNe --> aiNe : Performance Log
        }
        System_Boundary(rgWe, "Western Europe") {
            AzureFunction(afWe, "Hub-Redirect-fn-env-we", "Western Europe")
            AzureStorage( stWe, "Hub-Redirect-st-env-we", "Western Europe")
            AzureApplicationInsights( aiWe, "Hub-Redirect-ai-env-we", "Western Europe")

            afWe --> stWe : App/Log Storage
            afWe --> aiWe : Performance Log
        }

        tm -[hidden]down-> rgNe
        tm -[hidden]down-> rgWe
    }

    AzureVirtualMachine(vm, "https://env.hub.knightfrank.com/", "Env")

    afNe -up-> vm : Proxied request
    afWe -up-> vm : Proxied request
}

out -down-> tm : Dns Lookup
tm -up-> out : Address of resource

out --> afNe 
out --> afWe

@enduml