@startuml Claim Check
!includeurl https://raw.githubusercontent.com/aheil/EIP-PlantUML/master/dist/EIP-PlantUML.puml

LAYOUT_LEFT_RIGHT()

Message( msgI, "Message W\ Data")
rectangle find as "Find"
MessageFilter( add, "Address")
Message( msga, "Message")
MessageFilter( nadd, "not Address")
Message( msgna, "Message")
rectangle retrieve as "Retrieve"
Message( msgO, "Message")

msgI --> find
find --> add
add --> msga
find --> nadd
nadd --> msgna

msga --> find
msgna --> retrieve
retrieve --> msgO







@enduml