@startuml

title "SQL Integrated Change Tracking - Sequence Diagram"

activate hub
actor hub
Database  SQL
activate Webjob
Webjob -> SQL : Connect
hub -> SQL
Webjob -> SQL : Get Changes
return
Database ElasticSearch
Webjob -> ElasticSearch : Send Changes
return

Webjob -> SQL : Disconnect
deactivate Webjob
deactivate hub


@enduml