@startuml Template Masking

allow_mixing

Interface BaseDs
BaseDs <|-- OfferDs
BaseDs <|-- RequirementDs
BaseDs <|-- ActivityDs

Interface IDataSourceBuilder
IDataSourceBuilder : BuildOfferDS
IDataSourceBuilder : BuildRequirementDS
IDataSourceBuilder : BuildActivityDS

IDataSourceBuilder <|-- DataSourceBuilder
IDataSourceBuilder -right-> BaseDs

DataSourceBuilder : BuildOfferDS
DataSourceBuilder : BuildRequirementDS
DataSourceBuilder : BuildActivityDS

DataSourceBuilder -up-> OfferDs
DataSourceBuilder -up-> RequirementDs
DataSourceBuilder -up-> ActivityDs

OfferDocumentGeneratorBehaviour : GetOffer
OfferDocumentGeneratorBehaviour : GetRequirement
OfferDocumentGeneratorBehaviour : GetActivity

Interface IDocumentGeneratorBehaviour
IDocumentGeneratorBehaviour <|-- OfferDocumentGeneratorBehaviour
OfferDocumentGeneratorBehaviour -right-> IDataSourceBuilder

Interface ISecurityValidator
ISecurityValidator <|-- SecurityValidator
OfferDocumentGeneratorBehaviour -left-> SecurityValidator

Database IReadGenericRepository
OfferDocumentGeneratorBehaviour --> IReadGenericRepository

'Interface IEntityValidator
'IEntityValidator <|-- EntityValidator
'OfferDocumentGeneratorBehaviour -left-> EntityValidator

@enduml