@startuml TextMessage

allow_mixing

!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Databases/all.puml
!includeurl AzurePuml/Web/all.puml
!includeurl AzurePuml/Storage/all.puml

LAYOUT_TOP_DOWN
'LAYOUT_WITH_LEGEND

Actor hub
AzureQueueStorage(aqs, "Queue", "Technology", "Optional Description")
AzureWebApp(awa, "WebJob", "Technology", "Optional Description")

hub -> aqs
aqs -> awa
awa -> SMSService


'Interface ITextMessageWebJobModule
'Interface ITextMessageRecipientValidator

'Module --> TextMessageWebJobModule
'Module --> TextMessageRecipientValidator

'ITextMessageWebJobModule <|-- TextMessageWebJobModule
'ITextMessageRecipientValidator <|-- TextMessageRecipientValidator


'Interface IMessagingClient
'IMessagingClient : MessageResource SendMessage(string recipientNumber, string body);

'IMessagingClient <|-- MessagingClient 
'MessagingClient : MessageResource SendMessage(string recipientNumber, string body)}
'IMessagingClient -right-> IServcieProvider

'Interface IServcieProvider
'IServcieProvider <|-- SvcSMSSpeedway
'IServcieProvider <|-- Twilio 


'Interface IRequestHandler
'IRequestHandler : Handle()
'TextMessageQuery <.. IRequestHandler
'TextMessageViewModel <.. IRequestHandler
'IRequestHandler <|-- TextMessageQueryHandler

'TextMessageQueryHandler : Handle(TextMessageQuery query)
'TextMessageQueryHandler : ApplySecurity(TextMessageViewModel textMessage)


'BaseController <|-- TextMessagesController


' Interfaces, Classes, Methods
Interface INotification
Interface INotificationHandler 
Class TextMessageOutboxedEvent
Class TextMessageOutboxedEventHandler
'Class TextMessageViewModel

INotification : mediate()
TextMessageOutboxedEventHandler : Handle() 

' Relationship
INotification <- INotificationHandler : mediator
INotification -[hidden]-> TextMessageOutboxedEventHandler

INotification <|-- TextMessageOutboxedEvent : Implements
INotificationHandler <|-- TextMessageOutboxedEventHandler : Implements
TextMessageOutboxedEvent -> TextMessageOutboxedEventHandler

' =======================

' Interfaces, Classes, Methods
Interface IRequest 
interface IRequestHandler
Class TextMessageCommandBase
Class TextMessageQueryHandler
Class CreateTextMessageCommandHandler

IRequest : mediate()
CreateTextMessageCommandHandler : Handle()

' Relationship
IRequest <- IRequestHandler : mediator
IRequest -[hidden]-> TextMessageQueryHandler

IRequest <|-- TextMessageCommandBase
IRequestHandler <|-- TextMessageQueryHandler : Implements
CreateTextMessageCommand -> CreateTextMessageCommandHandler
TextMessageQueryHandler <|-- CreateTextMessageCommandHandler : Implements
TextMessageCommandBase -> TextMessageQueryHandler



@enduml
