@startuml ehouse Order Sequence

participant hub
participant SvcQueue
participant Svc
participant ehouse
participant Table

alt Register Webhooks
Svc -> ehouse : register stills webhook
Svc -> ehouse : register Videos webhook
Svc -> ehouse : register Floorplans webhook
Svc -> ehouse : register VirtualTours webhook
end 


hub -> SvcQueue
SvcQueue -> Svc
Activate Svc

alt Creation
Svc -> ehouse : Get Key Invoice items
Svc <-- ehouse : Response 2xx Success


Svc -> ehouse : Post Create Order 
Svc <-- ehouse : Response 2xx Success
Svc --> ehouse : Post Get Available Photographer Bookings
Svc <-- ehouse : Response 2xx Success
Svc --> ehouse : Post Book Photographer
Svc <-- ehouse : Response 2xx Success
Svc --> ehouse : Post Create WebHook
Svc <-- ehouse : Response 2xx Success

Svc -> Table : Update details in Table Store

else Update
Svc -> ehouse : Post Update Order
end


alt WebHook Stills
ehouse -> Svc : Stills ready
Svc -> ehouse : Get Stills
Svc <-- ehouse : Response 2xx Success
end

alt WebHook Videos
ehouse -> Svc : Videos ready
Svc -> ehouse : Get Videos
Svc <-- ehouse : Response 2xx Success
end

alt WebHook Floorplans
ehouse -> Svc : Floorplans ready
Svc -> ehouse : Get Floorplans
Svc <-- ehouse : Response 2xx Success
end

alt WebHook VirtualTours
ehouse -> Svc : VirtualTours ready
Svc -> ehouse : Get VirtualTours
Svc <-- ehouse : Response 2xx Success
end

Svc -> Table : Update details in Table Store
Svc -> SvcQueue : Return Data Error to hub


Deactivate Svc



@enduml