@startuml Created Note Event

class NoteCreatedDeletedEventHandler {
    + NoteCreatedDeletedEventHandler(elasticFeedQueueMessageClient:IQueueMessageClient<ElasticSearchQueueMessage>)
    + Handle(@event:NoteCreatedEvent) : void
    + Handle(@event:NoteDeletedEvent) : void
}
class "INotificationHandler"<T> {
}
"INotificationHandler" "<NoteCreatedEvent>" <|-- NoteCreatedDeletedEventHandler
'"INotificationHandler" "<NoteDeletedEvent>" <|-- NoteCreatedDeletedEventHandler

class NoteCreatedEvent {
    + Content : string <<get>> <<set>>
    + NoteCreatedEvent(note:Note, relatedEntityType:EntityType, entityId:Guid)
}
INotification <|-- NoteCreatedEvent
'NoteCreatedEvent --> "Id" Guid
'NoteCreatedEvent --> "RelatedEntityType" EntityType
'NoteCreatedEvent --> "EntityId" Guid

INotification <- INotificationHandler : mediator
NoteCreatedEvent -> NoteCreatedDeletedEventHandler

@enduml