@startuml
class BuildingBreakdownPropertyQueryHandler {
}
class "IRequestHandler`2"<T1,T2> {
}
"IRequestHandler`2" "<BuildingBreakdownPropertyQuery,BuildingBreakdownPropertyViewModel>" <|-- BuildingBreakdownPropertyQueryHandler
@enduml
