@startuml Activity

' (Contact) as (Seller)
' (Contact) as (Buyer)
' (Contact) as (Owner)

(Seller) <-up- (Activity) : Seller/Lessor/\nLandlord
(Buyer) <-up- (Activity) : Buyer/Lessee/\nTenant
(Activity) -> (Asset)
(Asset) <- (Owner) : Has a\nOwner

@enduml