@startuml Contact

(Contact) -> (Contact) : Relationship With

(Pitch) --> (Contact) : To a Contact
(Referral) <-- (Contact) : By a Contact
(Requirement) <-- (Contact) : From a Contact
(Instruction) <-- (Contact) : From a Contact

(Contact) --> (Activity) : Party To
(Contact) --> (Asset) : Owner/Seller/Buyer/Tenant

(Activity) -> (Asset)

@enduml