@startuml Real Estate

(Contact) --> (Activity) : Party To
(Contact) --> (Asset) : Owner/Seller/Buyer/Tenant
(Activity) -> (Asset) : Acting On

(Contact) -> (Contact) : Relationship With
(Asset) -> (Asset) : Sub-Asset

@enduml