@startuml Instruction

(Contact) as (ClientParty)
(Contact) as (KfParty)

(ClientParty) --> (Instruction) : Instructing Party
(KfParty) --> (Instruction) : KF Party
(Instruction) --> (Asset) : Instructed Asset

@enduml