@startuml Instruction

(Buyer) << Contact >>
(Agent) << Contact >>

(Buyer) --> (Instruction) : Instructing Party
(Agent) --> (Instruction) : KF Party
(Instruction) --> (Asset) : Instructed Asset

@enduml