@startuml Referral

(Seller) << Contact >>
(Agent) << Contact >>
(Referred) << Contact >>

(Seller) --> (Referral) : Referring Party
(Agent) --> (Referral) : KF Party
(Referral) --> (Asset) : Referred Asset
(Referral) --> (Referred) : Referred Contact


@enduml