@startuml Requirement

' (Contact) as (Agent)
' (Contact) as (Buyer)

(Buyer) --> (Requirement) : Requiring Party
(Agent) --> (Requirement) : KF Party
(Requirement) --> (Asset) : Required Synthetic\nAsset
 
@enduml