@startuml
class UpdateTenancyCommandHandler {
}
class "IRequestHandler`2"<T1,T2> {
}
"IRequestHandler`2" "<UpdateTenancyCommand,CreateOrUpdateTenancyCommandResult>" <|-- UpdateTenancyCommandHandler
@enduml
