@startuml "hubcdd Container"

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Integration/AzureEventGrid.puml
!includeurl AzurePuml/Storage/AzureQueueStorage.puml

LAYOUT_TOP_DOWN

Person(user, "User")
System_Boundary(hub, "Hub System") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
    ContainerDb(SqlDb, "Hub Sql Database", "Sql Server")

    System_Boundary(az, "Azure") {
        ContainerDb(BlobDb, "Blob Storage", "Blob Storage")
    }
}

System_Boundary(azs, "ImageAnlysis Service") {
    ContainerDb(TableDb, "Table Storage", "Table Storage")

    AzureFunction(fnSqlUpdate, "Image Update", "C#")
    AzureQueueStorage(queue, "Images to Process", "C#")
    AzureFunction(fnRestbai, "Image Analysis", "C#")
}
System(restbai, "Restb.ai")

Rel(user, web_app, "Uses", "HTTPS")
Rel(web_app, SqlDb, "Updates image Metadata", "HTTPS")
Rel(web_app, BlobDb, "Updates image file", "HTTPS")

fnSqlUpdate -Down-> SqlDb : Gets
fnSqlUpdate -Down-> TableDb : Upsert
fnSqlUpdate -Down-> BlobDb : Get
fnSqlUpdate -Up-> queue


queue -Down-> fnRestbai
fnRestbai -Down-> TableDb : Update
fnRestbai -> restbai : Calls /\n Rate Limited

web_app -Down->  TableDb : DashBoard

BlobDb --> fnSqlUpdate : Blob Trigger
web_app -> fnSqlUpdate : User Trigger
@enduml