@startuml

title CDD Job Priority ERD 

left to right direction

!define table(x) class x << (T,mistyrose) >>   
!define view(x) class x << (V,lightblue) >>   
!define table(x) class x << (T,mistyrose) >>  
!define tr(x) class x << (R,red) >>  
!define tf(x) class x << (F,darkorange) >>   
!define af(x) class x << (F,white) >>   
!define fn(x) class x << (F,plum) >>   
!define fs(x) class x << (F,tan) >>   
!define ft(x) class x << (F,wheat) >>   
!define if(x) class x << (F,gaisboro) >>   
!define p(x) class x << (P,indianred) >>   
!define pc(x) class x << (P,lemonshiffon) >>   
!define x(x) class x << (P,linen) >>     
!define primary_key(x) <<pk>> <u>x</u>
!define foreign_key(x) <<fk>> <b>x</b>
!define link( k, y) k }--||  y
hide methods   
hide stereotypes  
skinparam classarrowcolor gray  

table(User)
{
    primary_key(Id)
}

table(Contact)
{
    primary_key(Id)
}

table(Company)
{
    primary_key(Id)
}

table(CDD)
{
    primary_key(Id)
    ContactId
    CompanyId
    ExpiryDate
    Valid
    RiskRating
    DocumentId
}

table( CddJob)
{
    primary_key(Id)
    UserId
    CDDId
    NextActionId
    ActionTypeId
    -Priority
}

table(Action)
{
    primary_key(Id)
    ActionOwnerId
    CddJobId
    Action
    ExpectedCompletionDate
    
}

table(EnumTypeItem)
{
    primary_key(Id)
}

table( CDDQuestionnaire)
{
    primary_key(Id)
    CDDId
    QuestionnaireId
}
table(Questionnaire)
{
    primary_key(Id)
}


User ||--|{ CddJob : A User can have many Cdd Jobs
CddJob ||--|| CDD : A CddJob has a CDD
CddJob ||--|{ EnumTypeItem : ActionType
CddJob ||--|{ Action : A CddJob has Action's\n A Action has a CddJob

Action ||--|| User : A Action has a User 

Contact ||--|{ CDD : A contact can have many CDDs
Company ||--|{ CDD : A Company can have many CDDs

CDD ||--|{ CDDQuestionnaire : A CDD has many Questionnaires
CDDQuestionnaire }|--|| Questionnaire : A Questionnaire has many CDD's

@enduml


