@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

'LAYOUT_WITH_LEGEND

title Container diagram for hub

Enterprise_Boundary(c1, "Knight Frank LLP") {
    Person(customer, "Knight Frank Employee ", "A employee working within Knight Frank")

    System_Boundary(hub_system, "hub System"){

        Container( hapi, "hub API", "")
        Container( hbll, "hub Bll", "Provides rules and ")
        ContainerDb( hdb, "hub data", "SQL")
        Container( napi, "CDD Service", "Provides Automated Due Diligence information on contacts and companies")
    }
    System(rep_system, "Reporting  System", "Power Bi Reporting")
}
System_Ext(northrow, "Northrow", "Automated Due Diligence")

Rel(customer, hapi, "Uses")
Rel(hapi, hbll, "Uses")
Rel(hbll, hdb, "Uses")
Rel(hbll, napi, "Uses")
Rel(napi, northrow, "Uses")
Rel_L(hbll, rep_system, "Uses")


@enduml