@startuml

title CDD Questionnaire 

left to right direction

!define table(x) class x << (T,mistyrose) >>   
!define view(x) class x << (V,lightblue) >>   
!define table(x) class x << (T,mistyrose) >>  
!define tr(x) class x << (R,red) >>  
!define tf(x) class x << (F,darkorange) >>   
!define af(x) class x << (F,white) >>   
!define fn(x) class x << (F,plum) >>   
!define fs(x) class x << (F,tan) >>   
!define ft(x) class x << (F,wheat) >>   
!define if(x) class x << (F,gaisboro) >>   
!define p(x) class x << (P,indianred) >>   
!define pc(x) class x << (P,lemonshiffon) >>   
!define x(x) class x << (P,linen) >>     
!define primary_key(x) <<pk>> <u>x</u>
!define foreign_key(x) <<fk>> <b>x</b>
!define link( k, y) k }--||  y
hide methods   
hide stereotypes  
skinparam classarrowcolor gray  


table(Contact)
{
    primary_key(Id)
}

table( Activity)
{
    primary_key(Id)
}

table( ActivityQuestionnaire)
{
    primary_key(Id)
    ActivityId
    QuestionnaireId
}

table(CDD)
{
    primary_key(Id)
    ContactId
    ExpiryDate
    QuestionnaireId
    DocumentId
}

table( QuestionnaireType)
{
    primary_key(Id)
}

table( Questionnaire)
{
    primary_key(Id)
    QuestionnaireTypeId
}

table( Question)
{
    primary_key(Id)
    QuestionnaireTypeId
}

table( QuestionAnswer)
{
    primary_key(Id)
    QuestionnaireId 
    QuestionId
    CDDId
}

Contact ||--|{ CDD : A contact can have many CDDs

CDD ||--|| Questionnaire 
CDD ||--|{ QuestionAnswer : A ContactCDD has many Answers \n A Answer has 1 contact

Activity ||--|{ ActivityQuestionnaire : A Activity has many Questionnaires \n A Questionnaire has 1 Activity
ActivityQuestionnaire ||--|| Questionnaire

Questionnaire ||--|{ QuestionAnswer : A Questionnaire has many Answers \n A Answer has 1 Questionnaire
Question ||--|{ QuestionAnswer : A Question has Many Answers \n A Answer has 1 Question

QuestionnaireType ||--|{ Question : QuestionnaireType has many Questions
QuestionnaireType ||--|{ Questionnaire : A Questionnaire is a instance of a QuestionnaireType
@enduml