@startuml CDDProcess

title CDD-Process

'left to right direction

(start) --> CounterParty
CounterParty --> (Offer) : Makes Offer
(Offer) --> Party : Offer Passed\nto Party/Seller
Party --> (Accept) : 1, Instruction\nCompleted
(Accept) --> (CDD Request) : 2, Trigger CDD Request
(Accept) --> Negotiator : 3, Add\nInformation
Negotiator --> (?) : Not sure what\n to do now
(CDD Request) --> (DashBoard) : 4, CDD Request
(DashBoard) --> CDD_Admin
CDD_Admin --> CDD_Officer : 5, Assign
Party --> (Withdraw) : 6, Notify
(Withdraw) --> CDD_Officer : 6. Notify
(CDD Request) --> CDD_Officer : 7. Confirm and Check
CDD_Officer --> (Completed)
CDD_Officer --> (?) : Withdraw\nNot sure what\n to do now
(Completed) --> (Activity Status) : 8. Exchanged/Completed
(Activity Status) --> (end)

' state "CounterParty" as CounterParty
' state "Offer" as Offer
' state "Party" as Party
' state "Accept" as Accept
' state "CDD Request" as CDDRequest
' state "Negotiator" as Negotiator
' state "DashBoard" as DashBoard
' state "CDD_Admin" as CDD_Admin
' state "Withdraw" as Withdraw
' state "CDD_Officer" as CDD_Officer
' state "Completed" as Completed
' state "CDD_Officer" as CDD_Officer
' state "Activity Status" as ActivityStatus
' state "?" as quest

' [*] --> CounterParty
' CounterParty --> Offer
' Offer --> Party
' Party --> Accept
' Accept --> CDDRequest
' Accept --> Negotiator
' Negotiator --> quest
' CDDRequest --> DashBoard
' DashBoard --> CDD_Admin
' CDD_Admin --> CDD_Officer
' Party --> Withdraw
' Withdraw --> CDD_Officer
' CDD_Officer --> Completed
' CDD_Officer --> quest
' Completed --> ActivityStatus
' ActivityStatus --> [*]


@enduml