@startuml

title CDD New 

left to right direction

!define newtable(x) class x << (T,LimeGreen) >> 

!define table(x) class x << (T,mistyrose) >>   
!define view(x) class x << (V,lightblue) >>   
!define table(x) class x << (T,mistyrose) >>  
!define tr(x) class x << (R,red) >>  
!define tf(x) class x << (F,darkorange) >>   
!define af(x) class x << (F,white) >>   
!define fn(x) class x << (F,plum) >>   
!define fs(x) class x << (F,tan) >>   
!define ft(x) class x << (F,wheat) >>   
!define if(x) class x << (F,gaisboro) >>   
!define p(x) class x << (P,indianred) >>   
!define pc(x) class x << (P,lemonshiffon) >>   
!define x(x) class x << (P,linen) >>     
!define primary_key(x) <<pk>> <u>x</u>
!define foreign_key(x) <<fk>> <b>x</b>
!define link( k, y) k }--||  y
hide methods   
hide stereotypes  
skinparam classarrowcolor gray  

table( Activity)
{
    primary_key(Id)
    CddId
}

table( Instruction)
{
    primary_key(Id)
    CddId
}

table( Requirement)
{
    primary_key(Id)
    CddId
}

table(EnumTypeItem)
{
    primary_key(Id)
}

newtable( QuestionTemplate)
{
    primary_key(Id)
    QuestionnaireTypeId
    ActiveDate
    Version
}

table( Questionnaire)
{
    primary_key(Id)
    StatusId
    SubmittedByUserId
    Version
    SubmittedTime
    QuestionnaireTemplateId
}

table( Question)
{
    primary_key(Id)
    TitleId
    SectionTitleId
    TranslationId
    AnswerTypeId
}

table( QuestionAnswer)
{
    primary_key(Id)
    QuestionnaireId 
    QuestionId
}

table( QuestionNote)
{
    primary_key(QuestionnaireId)
    NoteId
}

newtable( CDD)
{
    primary_key(Id)
    CddStatusId
    QuestionnaireId
    TeamResponsibleForCddId
    CddCompleteId
    RequireCdd
    EntityId
    EntityTypeId
}

'newtable( CDDEntity)
'{
'    primary_key(Id)
'    EntityId
'    EntityTypeId
'    CddId
'}

Activity ||--|| CDD #line:green
Instruction ||--|| CDD #line:green
Requirement ||--|| CDD #line:green

CDD ||--|{ EnumTypeItem #line:red; : CddStatusId (Pending, Complete...)
CDD ||--|| Questionnaire #line:green : A CDD has a Questionnaire
CDD ||--|{ EnumTypeItem #line:red; : TeamResponsibleForCddId (CentralCdd,Office)
CDD ||--|{ EnumTypeItem #line:red; : CddCompleteId (Yes,No,preCentralisation)
CDD ||--|{ EnumTypeItem #line:red; : EntityTypeId (Activity,Instruction...)

Questionnaire ||--|{ QuestionAnswer : A Question has Many QuestionAnswer
Questionnaire ||--|{ QuestionNote : A Questionnaire can have many Notes
Question ||--|{ QuestionAnswer : A Question has Many QuestionAnswers
Questionnaire ||--|{ EnumTypeItem : StatusId (None,NotSubmitted,Submitted)

QuestionTemplate ||--|{ Question #line:green : A Questionnaire can have many Questions
QuestionTemplate }|--|| Questionnaire #line:green; : QuestionnaireTemplateId
QuestionTemplate ||--|{ EnumTypeItem #line:green; : QuestionnaireTypeId (Disposal, Acquisition)


@enduml

