@startuml AssetTitle

left to right direction

!define table(x) class x << (T,mistyrose) >>   
!define view(x) class x << (V,lightblue) >>   
!define table(x) class x << (T,mistyrose) >>  
!define tr(x) class x << (R,red) >>  
!define tf(x) class x << (F,darkorange) >>   
!define af(x) class x << (F,white) >>   
!define fn(x) class x << (F,plum) >>   
!define fs(x) class x << (F,tan) >>   
!define ft(x) class x << (F,wheat) >>   
!define if(x) class x << (F,gaisboro) >>   
!define p(x) class x << (P,indianred) >>   
!define pc(x) class x << (P,lemonshiffon) >>   
!define x(x) class x << (P,linen) >>     
!define primary_key(x) <<pk>> <u>x</u>
!define foreign_key(x) <<fk>> <b>x</b>
!define link( k, y) k }--||  y
hide methods   
hide stereotypes  
skinparam classarrowcolor gray  

table( Contact)
{
    primary_key(Id)
    FileName
    LastName
}

table( Company)
{
    primary_key(Id)
    Name
    Description
    RegistrationNumber
    WebSiteUrl
    Email
}
table( CDD)
{
    primary_key(Id)
    ContactId
    CompanyId
    RAG
    ExpiryDate
}

table(CDDDocuments)
{
    primary_key(Id)
    CDDId
    DocumentId
}

table( Asset)
{
    primary_key(Id)
    AddressId
    AssetTitleId
}

table( AssetTitle)
{
    primary_key(Id)
    AssetId
    ContactId
    CompanyId
}

Contact ||--|{ CDD 
Company ||--|{ CDD

CDD ||--|{ CDDDocuments

Asset ||--|{ AssetTitle
AssetTitle ||--|{ Contact
AssetTitle ||--|{ Company



@enduml