@startuml "Cdd Component"

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

LAYOUT_TOP_DOWN

System_Ext( nr, "Northrow", "Automated Due Diligence service")

Container_Boundary(c1, "hub"){
    Container(hubWapp, "hub Web Application", "C#", "Allows users to view contacts, activities, properties, etc.")
    Container(hubApi, "hub Web API", "C#", "Allows users to view contacts, activities, properties, etc.")
    ContainerDb(cdb, "DataStore", "Azure TableStorage", "Stores information regarding the due diligence of contacts and companies")
    Container(nrSvc, "NorthRow Service", "Northrow Service Handler")

    Container_Boundary(c2, "CDD"){
        Component(api, "CddController", "C# MVC Controller", "")
        Component(bll, "Cdd Process", "C#", "Provides Automated Due Diligence information on contacts and companies")
        Component(tsh, "Table Storage", "C#", "Provides Table storage access, Encryption/Decryption")
        Component(svc, "CddService", "C#", "Provides Access to external service")
        Component(tim, "Scheduler", "C# Azure Function", "A Scheduled maintenance task to clean up expired information")

        Rel_D( api, bll, "Uses")
        Rel_D( bll, svc, "Uses")
        Rel_L( bll, tsh, "Uses")
        Rel_L( tsh, cdb, "Reads from\nand Writes to")
        Rel_U( bll, hubApi,"Uses", "JSON/HTTPS")
        Rel_L( tim, api, "Uses", "JSON/HTTPS")
    }

    Rel_D( hubWapp, hubApi,"Uses", "JSON/HTTPS")
    Rel_D( hubApi, api, "Uses", "JSON/HTTPS")
    Rel_D( svc, nrSvc, "Uses", "JSON/HTTPS")
    Rel_D( nrSvc, nr, "Uses", "JSON/HTTPS")
    cdb -[hidden]-> tsh
}

@enduml