@startuml
class CreateTenancyPartyCommand {
}
TenancyPartyCommand <|-- CreateTenancyPartyCommand
ICommandWithVersion <|-- CreateTenancyPartyCommand
ICreateUndisclosedPartyCommand <|-- CreateTenancyPartyCommand
@enduml
