@startuml
class TenancyPartyCommand {
}
class "IRequest`1"<T> {
}
BasePartyCommandWithGenericDescription <|-- TenancyPartyCommand
"IRequest`1" "<Guid>" <|-- TenancyPartyCommand
IPartyCommandWithUndisclosedAttributes <|-- TenancyPartyCommand
@enduml
