@startuml
class UpdateNotificationStatusCommandValidator {
    + UpdateNotificationStatusCommandValidator()
}
class "AbstractValidator"<T> {
}
"AbstractValidator" "<UpdateNotificationStatusCommand>" <|-- UpdateNotificationStatusCommandValidator
@enduml
